senders:
  - type: telegram
    patterns:
      labels:
        severity: critical
    telegram_bot_token: $TELEGRAM_BOT
    telegram_chat_id: $TELEGRAM_CHAT_ID
#  - type: rocketchat
#    alert_name_patterns:
#      - .*
#    rocketchat_webhook: $ROCKETCHAT_WEBHOOK